{{- if .Values.import.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-bootstrap-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ca-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  secretName: {{ .Release.Name }}-ca-secret
  isCA: true
  commonName: "SceneScape Root CA"
  subject:
    organizationalUnits:
      - {{ .Release.Namespace }}
    countries:
      - US
  duration: 43800h
  renewBefore: 720h
  issuerRef:
    name: {{ .Release.Name }}-bootstrap-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-ca-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  ca:
    secretName: {{ .Release.Name }}-ca-secret
{{- end }}
